"""add_listing_tables

Revision ID: 4ccbc432865c
Revises: f2d5d335a5ca
Create Date: 2026-03-22 20:43:16.676495

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4ccbc432865c'
down_revision: str | Sequence[str] | None = 'f2d5d335a5ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('rent_net', sa.Integer(), nullable=True),
    sa.Column('rent_gross', sa.Integer(), nullable=True),
    sa.Column('rent_charges', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('address_raw', sa.String(length=300), nullable=True),
    sa.Column('street', sa.String(length=150), nullable=True),
    sa.Column('house_number', sa.String(length=20), nullable=True),
    sa.Column('plz', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('offer_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_listings_source_id')
    )
    op.create_index(op.f('ix_listings_plz'), 'listings', ['plz'], unique=False)
    op.create_index(op.f('ix_listings_source'), 'listings', ['source'], unique=False)
    op.create_table('listing_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=500), nullable=True),
    sa.Column('new_value', sa.String(length=500), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_history_listing_id'), 'listing_history', ['listing_id'], unique=False)
    op.create_table('listing_unit_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('egid', sa.Integer(), nullable=False),
    sa.Column('ewid', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.String(length=20), nullable=False),
    sa.Column('matched_egid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_unit_matches_egid'), 'listing_unit_matches', ['egid'], unique=False)
    op.create_index(op.f('ix_listing_unit_matches_listing_id'), 'listing_unit_matches', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_unit_matches_listing_id'), table_name='listing_unit_matches')
    op.drop_index(op.f('ix_listing_unit_matches_egid'), table_name='listing_unit_matches')
    op.drop_table('listing_unit_matches')
    op.drop_index(op.f('ix_listing_history_listing_id'), table_name='listing_history')
    op.drop_table('listing_history')
    op.drop_index(op.f('ix_listings_source'), table_name='listings')
    op.drop_index(op.f('ix_listings_plz'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
