"""initial_schema

Revision ID: f2d5d335a5ca
Revises: 
Create Date: 2026-03-22 16:47:46.699139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2d5d335a5ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gwr_buildings',
    sa.Column('egid', sa.Integer(), nullable=False),
    sa.Column('gstat', sa.Integer(), nullable=True),
    sa.Column('gkat', sa.Integer(), nullable=True),
    sa.Column('gklas', sa.Integer(), nullable=True),
    sa.Column('gbauj', sa.Integer(), nullable=True),
    sa.Column('gabbj', sa.Integer(), nullable=True),
    sa.Column('garea', sa.Integer(), nullable=True),
    sa.Column('gastw', sa.Integer(), nullable=True),
    sa.Column('ganzwhg', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('municipality', sa.String(length=100), nullable=True),
    sa.Column('municipality_code', sa.Integer(), nullable=True),
    sa.Column('canton', sa.String(length=2), nullable=True),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('egid')
    )
    op.create_index(op.f('ix_gwr_buildings_egid'), 'gwr_buildings', ['egid'], unique=False)
    op.create_table('gwr_entrances',
    sa.Column('egid', sa.Integer(), nullable=False),
    sa.Column('edid', sa.Integer(), nullable=False),
    sa.Column('strname', sa.String(length=100), nullable=True),
    sa.Column('deinr', sa.String(length=20), nullable=True),
    sa.Column('dplz4', sa.Integer(), nullable=True),
    sa.Column('dplzname', sa.String(length=100), nullable=True),
    sa.Column('doffadr', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('egid', 'edid')
    )
    op.create_index(op.f('ix_gwr_entrances_egid'), 'gwr_entrances', ['egid'], unique=False)
    op.create_table('gwr_units',
    sa.Column('egid', sa.Integer(), nullable=False),
    sa.Column('ewid', sa.Integer(), nullable=False),
    sa.Column('edid', sa.Integer(), nullable=True),
    sa.Column('wstwk', sa.Integer(), nullable=True),
    sa.Column('wstwklang', sa.String(length=100), nullable=True),
    sa.Column('wazim', sa.Integer(), nullable=True),
    sa.Column('warea', sa.Integer(), nullable=True),
    sa.Column('wkche', sa.Integer(), nullable=True),
    sa.Column('wstat', sa.Integer(), nullable=True),
    sa.Column('wbauj', sa.Integer(), nullable=True),
    sa.Column('wabbj', sa.Integer(), nullable=True),
    sa.Column('dplz4', sa.Integer(), nullable=True),
    sa.Column('dplzname', sa.String(length=100), nullable=True),
    sa.Column('strname', sa.String(length=100), nullable=True),
    sa.Column('deinr', sa.String(length=20), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('egid', 'ewid')
    )
    op.create_index(op.f('ix_gwr_units_egid'), 'gwr_units', ['egid'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_type', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('buildings_upserted', sa.Integer(), nullable=False),
    sa.Column('entrances_upserted', sa.Integer(), nullable=False),
    sa.Column('units_upserted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_gwr_units_egid'), table_name='gwr_units')
    op.drop_table('gwr_units')
    op.drop_index(op.f('ix_gwr_entrances_egid'), table_name='gwr_entrances')
    op.drop_table('gwr_entrances')
    op.drop_index(op.f('ix_gwr_buildings_egid'), table_name='gwr_buildings')
    op.drop_table('gwr_buildings')
    # ### end Alembic commands ###
